### ISSUE TITLE
Exclude packages?

### ISSUE THREAD

**Issue by iredmail** [Stifler6996/apt-mirror#31]
Dear all,

Is it possible to exclude some packages with apt-mirror? For example, i don't want to download games, and many gnome/kde packages, etc. This can save a lot disk space for a local apt repo.

**Comment by Stifler6996** [comment]
Hi Zhang,
Currently it cannot, and to be honest, its probably out of scope of the purpose of apt-mirror's function. A replicated mirror means exactly that. We are doing our best to ensure that we don't miss anything, rather than filtering some items.

There is no function in apt-mirror for "sections" as part of the collection of files currently. Is it possible, maybe. I am aware that deb-mirror does have the function, for example: "--exclude-deb-section=regex" . So I guess without looking further, it could be optioned, however I have no idea how accurate this "sections" tag is, and if sections can have multiple tags and how "sections" tags are managed (if at all).

Maybe others can comment?

**Comment by iredmail** [comment]
Thanks for the feedback. I can live with this, just disk is almost full. :(
